name: naqdi
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  carousel_slider: ^4.1.1

  provider: ^6.0.3

  action_slider: ^0.6.1
  slider_button: ^2.0.0

  intl_phone_field: ^3.1.0
  smooth_page_indicator: ^1.0.0+2
  intl: ^0.18.0
  shared_preferences: ^2.0.17


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
  # 
  # example:
  fonts:
    - family: Effra
      fonts:
        - asset: assets/fonts/alfont_com_Effra_Lt.ttf
          weight: 300
        - asset: assets/fonts/alfont_com_AlFont_com_Effra_Rg.ttf
          weight: 400
        - asset: assets/fonts/alfont_com_Effra_Md.ttf
          weight: 600
        - asset: assets/fonts/alfont_com_Dalton-Maag-Effra-Bold.ttf
          weight: 700
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
